CREATE DATABASE QuizGame
GO
USE QuizGame
GO
CREATE TABLE Answers (AnswerID int IDENTITY PRIMARY KEY,
                      Answer varchar(20))
CREATE TABLE QuestionTypes (TypeID int IDENTITY PRIMARY KEY,
                            Type varchar(20))

CREATE TABLE Questions (QuestionID int IDENTITY,
                        Question varchar(250),
                        A varchar(100),
                        B varchar(100),
                        C varchar(100),
                        D varchar(100),
                        Answer int REFERENCES Answers(AnswerID),
                        QuestionType int REFERENCES QuestionTypes(TypeID))

SELECT * FROM Questions
SELECT * FROM QuestionTypes
SELECT * FROM Answers

INSERT INTO Answers VALUES ('A'),('B'),('C'),('D')
INSERT INTO QuestionTypes VALUES ('Easy'),('Hard')

INSERT INTO Questions VALUES ('who is the author of the novel "Frankenstein"?',
                              'Mary Shelley',
                              'Sheridan Le Fanu',
                              'Bram Stoker',
                              'Ann Radcliffe',
                              2,
                              2),
                              ('Which ancient civilization invented writing?',
                              'Hittites',
                              'Elamites',
                              'Sumerians',
                              'Urartians',
                              3,
                              2),
                              ('Which country in South Asia was most affected by the tsunami disaster?',
                              'Indonesia',
                              'Sri Lanka',
                              'Thailand',
                              'India',
                              1,
                              1),
                              ('Which country has the largest population in the world?',
                              'India',
                              'China',
                              'United States',
                              'Indonesia',
                              2,
                              1),
                              ('Which number does not exist in Roman numerals?',
                              '0',
                              '50',
                              '100',
                              '1000',
                              1,
                              1),                                                              
                              ('Which country has two capitals?',
                              'Venezuela',
                              'Djibouti',
                              'El Salvador',
                              'South Africa',
                              4,
                              2),                                                    
                              ('Which river is the longest in the world?',
                              'Amazon',
                              'Nile',
                              'Yangtze',
                              'Mississippi',
                              2,
                              1),
                              
('Which planet is known as the "Red Planet"?',
                              'Earth',
                              'Jupiter',
                              'Mars',
                              'Venus',
                              3,
                              1),                                                    
                              ('Which city is considered sacred in all three major religions?',
                              'Mecca',
                              'Jerusalem',
                              'Rome',
                              'Istanbul',
                              2,
                              1),                                            
                              ('What is the raw material of aspirin?',
                              'Willow',
                              'Fir',
                              'Poplar',
                              'Oak',
                              1,
                              2)

SELECT Questions.QuestionID, Questions.Question, Questions.A, Questions.B, Questions.C, Questions.D, Questions.Answer, Answers.Answer, Questions.QuestionType, QuestionTypes.Type
FROM     Answers INNER JOIN
                  Questions ON Answers.AnswerID = Questions.Answer INNER JOIN
                  QuestionTypes ON Questions.QuestionType = QuestionTypes.TypeID
				  WHERE QuestionTypes.Type='Easy'

INSERT INTO Questions VALUES('Which city is known as the "Pearl of the Aegean" in Turkey?',
                              'Izmir',
                              'Antalya',
                              'Bursa',
                              'Mersin',
                              4,
                              2),('What is the first newspaper published with Latin letters?',
                              'Mardin Newspaper',
                              'Istanbul Newspaper',
                              'Ankara Newspaper',
                              'Burdur Newspaper',
                              1,
                              2),('If someone says "I visited all the capitals in Great Britain," which city have they not mentioned?',
                              'London',
                              'Dublin',
                              'Cardiff',
                              'Edinburgh',
                              2,
                              1),('Which one does not mean "definitely"?',
                              'Absolutely',
                              'Certainly',
                              'Alright',
                              'Always',
                              4,
                              1),('"Mid-August is summer" continues how?',
                              'Half is fall',
                              'Half is spring',
                              'Half is winter',
                              'Half is summer',
                              3,
                              1),('In a 2008 study by Newcastle University on 556,387 people and 927 family trees, what was found to have a higher chance of having male children than female children?',
                              'Women with more sisters',
                              'Men with more sisters',
                              'Women with more brothers',
                              'Men with more brothers',
                              4,
                              2),('Which type of pigeon is mentioned in an idiom?',
                              'Lark cuckoo',
                              'Oat crane',
                              'Sparrow hawk',
                              'Songbird',
                              3,
                              1),('Which strait separates Europe from Asia?',
                              'Strait of Gibraltar',
                              'Strait of Malacca',
                              'Bosporus Strait',
                              'Bab-el-Mandeb Strait',
                              3,
                              1),('What unique reason led to Michael Jordan briefly retiring from basketball in 1993?',
                              'Injury',
                              'Pursuit of a baseball career',
                              'Conflict with coach',
                              'Family reasons',
                              2,
                              2),('What does "noteworthy" mean?',
                              'Valuable',
                              'Unimportant',
                              'Simple',
                              'Careless',
                              1,
                              1)

INSERT INTO Questions VALUES('Which one is a type of bitter honey?',
                              'Mad honey',
                              'Lover honey',
                              'Passionate honey',
                              'Crazy honey',
                              1,
                              1),('Which one is not a fundamental particle in atoms?',
                              'Proton',
                              'Neutron',
                              'Electron',
                              'Megatron',
                              4,
                              1),('Which famous painter never visited France during his lifetime?',
                              'Vincent van Gogh',
                              'Claude Monet',
                              'Pablo Picasso',
                              'Frida Kahlo',
                              4,
                              2),('In 1959, which woman, disguised as a man, participated in a championship in New York and won a gold medal in judo, only to have to return it once her gender was discovered?',
                              'Chess',
                              'Judo',
                              'Fencing',
                              'Archery',
                              2,
                              2),('Which country was the first to grant women the right to vote?',
                              'United States',
                              'New Zealand',
                              'United Kingdom',
                              'Canada',
                              2,
                              2),('If someone travels from France by train and passes through the Channel Tunnel, where will they end up?',
                              'United Kingdom',
                              'Germany',
                              'Iceland',
                              'Portugal',
                              1,
                              1),('What is the movie with "the longest continuous film shoot" record in the Guinness World Records?',
                              'Winter Sleep',
                              'Pulp Fiction',
                              'Eyes Wide Shut',
                              'Heavy Novel',
                              3,
                              2),('What sport does someone play if they win the "Roland-Garros Championship"?',
                              'Tennis',
                              'Golf',
                              'Billiards',
                              'Boxing',
                              1,
                              1),('Which country is home to Mount Kenya, the second-highest peak in Africa after Kilimanjaro?',
                              'Kenya',
                              'South Africa',
                              'Nigeria',
                              'Morocco',
                              1,
                              1),('What is a nickname for carrots?',
                              'Rootworm',
                              'Ground hider',
                              'Soil diver',
                              'Black donkey',
                              3,
                              1)
